---
- hosts: web_server
  gather_facts: true
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.apt:
      update_cache: yes

  - name: install security updates
    ansible.builtin.apt:
      upgrade: yes

  - name: install apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest

  - name: install support for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest

  - name: perform full upgrade
    ansible.builtin.apt:
      upgrade: dist

  - name: ensure apache is running
    ansible.builtin.service:
      name: apache2
      state: started

  - name: copy html file for site
    ansible.builtin.copy:
      src: files/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: copy css file for site
    ansible.builtin.copy:
      src: files/styles.css
      dest: /var/www/html/styles.css
      owner: root
      group: root
      mode: 0644
