---
- hosts: all
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: Display distribution info
      debug:
        msg: "Running on {{ ansible_facts['distribution'] }}"

    - name: Update apt repository on Ubuntu
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: true
      become_user: root
      tags:
        - update
      # This task updates the apt repository cache for Ubuntu

    - name: Perform full upgrade on Ubuntu
      ansible.builtin.apt:
        upgrade: full
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: true
      become_user: root
      tags:
        - upgrade
      # This task performs a full upgrade of all packages on Ubuntu

    - name: Update dnf repository on Fedora
      ansible.builtin.dnf:
        update_cache: yes
      when: ansible_facts['distribution'] == 'Fedora'
      become: true
      become_user: root
      tags:
        - update
      # This task updates the dnf repository cache for Fedora

    - name: Perform full upgrade on Fedora
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] == 'Fedora'
      become: true
      become_user: root
      tags:
        - upgrade
      # This task performs a full upgrade of all packages on Fedora
