---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates and upgrades for Fedora using DNF
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: install updates and upgrades for Fedora using YUM
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: install updates and upgrades for Ubuntu
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install updates and upgrades for Rocky Linux using DNF
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution == "Rocky"

    - name: install updates and upgrades for Rocky Linux using YUM
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution == "Rocky"

    - name: install updates and upgrades for Pop!_OS
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Pop!_OS"

    - name: install updates and upgrades for Red Hat using DNF
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution in ["RedHat", "RedHatEnterprise"]

    - name: install updates and upgrades for Red Hat using YUM
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution in ["RedHat", "RedHatEnterprise"]

    - name: install updates and upgrades for Amazon Linux using DNF
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Amazon"]

    - name: install updates and upgrades for Amazon Linux using YUM
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Amazon"]
